service: aws-crud-api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${sls:stage}
    TABLE_NAME: ${param:tableName}
    LOG_LEVEL: ${param:logLevel}
    IS_OFFLINE: ${env:IS_OFFLINE, 'false'}

params:
  dev:
    tableName: ${self:service}-dev-items
    logLevel: DEBUG
  prod:
    tableName: ${self:service}-prod-items
    logLevel: INFO

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node18
    platform: node
    concurrency: 10

functions:
  createOrder:
    handler: src/handlers/createOrders.handler
    events:
      - httpApi:
          method: POST
          path: /orders
