name: Deploy prod

on:
  push:
    branches: ['main']

concurrency:
  group: deploy-prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: us-east-1
      SLS_TELEMETRY_DISABLED: '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Final checks before deploy
        run: npx tsc --noEmit && npm test -- --coverage --maxWorkers=2

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Deploy to AWS (prod)
        run: npx serverless deploy --stage prod --region $AWS_REGION
